services:
  - type: web
    name: pdf-rag-chatbot
    env: python
    buildCommand: pip install -r requirements-minimal.txt
    startCommand: python rag_server.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: OPENAI_MODEL
        value: gpt-4o